version: "3.3"

services:
  reactapp:
    build: .
    container_name: react-docker
    ports:
      - 3000:3000
    volumes: # seems not to be working on windows wsl2 for some reason
      - ./:/home/app