name: Firebase Web CI

on: push

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Install dependencies
      - name: yarn install
        run: |
          yarn
      ## Build & Deploy
      - name: Build & Deploy
        run: |
          REACT_APP_API_KEY_FOR_GMAPS=${{ SECRETS.REACT_APP_API_KEY_FOR_GMAPS }} REACT_APP_API_KEY_FOR_WEATHER=${{ SECRETS.REACT_APP_API_KEY_FOR_WEATHER }} yarn build
          firebase deploy --only hosting --token ${{ SECRETS.FIREBASE_TOKEN }} --message "$FIREBASE_MESSAGE" 
